FROM flink:1.19

COPY flink-sql-connector-postgres-cdc-3.2.1.jar /opt/flink/lib/flink-sql-connector-postgres-cdc-3.2.1.jar
COPY /target/transactions-1.0-SNAPSHOT.jar /opt/flink/usrlib/transactions.jar